### ISSUE TITLE
Install fails with ImportError

### ISSUE THREAD

**Issue by mfarnham** [isgilman/MiniContourFinder#27]
```bash
   ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/s9/bzpmt20145g694gc8qk3md8h0000gn/T/pip-install-jd0sd5i3/pytesseract/setup.py'"'"'; __file__='"'"'/private/var/folders/s9/bzpmt20145g694gc8qk3md8h0000gn/T/pip-install-jd0sd5i3/pytesseract/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/s9/bzpmt20145g694gc8qk3md8h0000gn/T/pip-install-jd0sd5i3/pytesseract/
    Complete output (42 lines):
    Traceback (most recent call last):
      File "/private/var/folders/s9/bzpmt20145g694gc8qk3md8h0000gn/T/pip-install-jd0sd5i3/pytesseract/pytesseract/pytesseract.py", line 26, in <module>
        from PIL import Image
    ModuleNotFoundError: No module named 'PIL'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/s9/bzpmt20145g694gc8qk3md8h0000gn/T/pip-install-jd0sd5i3/pytesseract/setup.py", line 4, in <module>
        setup()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/dist.py", line 699, in parse_config_files
        parse_configuration(self, self.command_options,
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/config.py", line 120, in parse_configuration
        meta.parse()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/config.py", line 425, in parse
        section_parser_method(section_options)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/config.py", line 398, in parse_section
        self[name] = value
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/config.py", line 183, in __setitem__
        value = parser(value)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/config.py", line 513, in _parse_version
        version = self._parse_attr(value, self.package_dir)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/config.py", line 348, in _parse_attr
        module = import_module(module_name)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/private/var/folders/s9/bzpmt20145g694gc8qk3md8h0000gn/T/pip-install-jd0sd5i3/pytesseract/pytesseract/__init__.py", line 2, in <module>
        from .pytesseract import ALTONotSupported
      File "/private/var/folders/s9/bzpmt20145g694gc8qk3md8h0000gn/T/pip-install-jd0sd5i3/pytesseract/pytesseract/pytesseract.py", line 28, in <module>
        import Image
    ModuleNotFoundError: No module named 'Image'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by isgilman** [comment]
See [here](https://minicontourfinder.readthedocs.io/en/latest/installation.html#pip-install), particularly the `ModuleNotFoundError`
